### ISSUE TITLE
Replies Issues

### ISSUE THREAD

**Issue by Ibal0512** [Philipinho/GetVideoBot#5]
replies simply update status, instead of replying to the mention directly.
pls help

**Comment by Philipinho** [comment]
Did you make any modifications to the Bot.java file?
One the `replyTweet(String text, String id)`, the `id` belongs to the tweet the bot is replying to.

**Comment by Ibal0512** [comment]
> Did you make any modifications to the Bot.java file?
> One the `replyTweet(String text, String id)`, the `id` belongs to the tweet the bot is replying to.

No, I didnt. Its exactly as it is.

**Comment by Philipinho** [comment]
Please share a link to the Twitter account where it was tested so I can have a look.

**Comment by Ibal0512** [comment]
> Please share a link to the Twitter account where it was tested so I can have a look.

Its a third party account. I am the dev. what could possibly be the cause from the account?

**Comment by Philipinho** [comment]
Have you been able to get it to work? 
I've checked the code and seem not to find a probable cause.

**Comment by Ibal0512** [comment]
> Have you been able to get it to work?
> I've checked the code and seem not to find a probable cause.

Not at all. I also believe the code is okay. The replies appear on the bot account timeline, but doesn't appear on the timeline of who mentioned the bot. 
I think the issue is from Twitter, perhaps the account is required to have certain number of followers - my guess?
I came across similar issue raised on twitter dev forum

**Comment by Philipinho** [comment]
Okay, I see. Not an issue with the software itself. 
It seems the bot is  kinda shadow banned by Twitter.

Some users will get notification and some won't.

That is often temporary as Twitter will get use to the bot with time.
