### ISSUE TITLE
Support for images

### ISSUE THREAD

**Issue by Parikshit-Hooda** [Philipinho/GetVideoBot#7]
I understand that it says "Video" in the project title but can we have support for images too? This issue is a feature request rather than a bug.

**Comment by Parikshit-Hooda** [comment]
I could go through the code, devise a solution and raise a PR if it works for you.

**Comment by Philipinho** [comment]
Twitter users can already save photos natively.
I don't think this feature will be any useful.

**Comment by Parikshit-Hooda** [comment]
Right, thanks.
